#!/usr/bin/env python3
"""
update_et_data.py
Extend BAM PET (potential evapotranspiration) input file from 2016-12-31
to 2026-04-30 (end of WY2026).

Data source:
  The existing file was derived from GOES-based EDEN PET data (Jacobs 2008),
  with values closely matching the TAYLORRIVER station in TEF04 MySQL.
  The MySQL PET data only extends to 2010-12-31; the 2011-2016 portion of
  the existing file was generated by same-DOY climatological sampling from
  the 1999-2010 record.  We apply the same approach for 2017-2026.

Workflow:
  1. Load existing 1999-2016 PET file
  2. For each day in 2017-01-01 to 2026-04-30, sample randomly from the
     same (month, day) pool in the 1999-2016 record
     Falls back to same-month if pool < 2 (handles Feb 29 leap day)
  3. Append new values to existing data
  4. Print summary statistics
  5. Save to new file (skipped in --dry-run mode)

Usage:
  python update_et_data.py             # full run -- writes output file
  python update_et_data.py --dry-run   # stats only -- nothing written to disk

No database connection required.
"""

import sys
import numpy as np
import pandas as pd
from pathlib import Path

# -- Configuration -------------------------------------------------------------
EXTEND_START = '2017-01-01'
EXTEND_END   = '2026-04-30'

DATA_DIR = Path(__file__).resolve().parent.parent / 'data' / 'ET'
EXISTING = DATA_DIR / 'PET_1999-9-1_2016-12-31.csv'
OUT_FILE = DATA_DIR / 'PET_1999-9-1_2026-4-30.csv'
# ------------------------------------------------------------------------------

# Plausible annual mean range for Florida Bay PET (mm/day)
ANNUAL_PLAUSIBLE = (3.5, 5.5)


def load_existing():
    """Load the existing PET file; return as Series indexed by date."""
    df = pd.read_csv(EXISTING, parse_dates=['Time'], index_col='Time')
    df.index.name = 'date'
    series = df['PET']
    print("  Loaded: %s -> %s  (%d days,  NaNs: %d)"
          % (series.index[0].date(), series.index[-1].date(),
             len(series), int(series.isna().sum())))
    return series


def extend_by_climatology(series_existing):
    """
    For each day in EXTEND_START to EXTEND_END, draw one random value from
    the matching (month, day) pool in the existing record.
    Falls back to same-month pool if fewer than 2 same-DOY values.
    Returns Series for the new period only.
    """
    new_idx = pd.date_range(EXTEND_START, EXTEND_END, freq='D')
    rng     = np.random.default_rng(seed=42)
    values  = []

    for ts in new_idx:
        m, d = ts.month, ts.day
        pool = series_existing[
            (series_existing.index.month == m) &
            (series_existing.index.day   == d) &
            series_existing.notna()
        ]
        if len(pool) < 2:
            pool = series_existing[
                (series_existing.index.month == m) &
                series_existing.notna()
            ]
        if pool.empty:
            values.append(series_existing.mean())
        else:
            values.append(float(rng.choice(pool.values)))

    new_series = pd.Series(values, index=new_idx, name='PET')
    new_series.index.name = 'date'
    print("  Extended: %s -> %s  (%d days)"
          % (new_series.index[0].date(), new_series.index[-1].date(),
             len(new_series)))
    return new_series


def print_summary(series_existing, series_new, series_combined):
    """Print comparison statistics: annual means, monthly climatology, sanity."""
    sep = "=" * 68

    # -- 1. Annual means -------------------------------------------------------
    print("\n" + sep)
    print("1. ANNUAL MEAN PET (mm/day)")
    print(sep)
    ann_all = series_combined.resample('YE').mean()
    print(ann_all.round(3).to_string())

    ann_pre  = series_combined[:'2016-12-31'].resample('YE').mean().mean()
    ann_post = series_combined['2017-01-01':].resample('YE').mean().mean()
    print("\n  1999-2016 mean: %.3f mm/day" % ann_pre)
    print("  2017-2026 mean: %.3f mm/day" % ann_post)
    print("  Delta: %+.3f mm/day (%+.1f%%)"
          % (ann_post - ann_pre, (ann_post - ann_pre) / ann_pre * 100))

    # -- 2. Monthly climatology -----------------------------------------------
    print("\n" + sep)
    print("2. MONTHLY CLIMATOLOGY -- mean PET (mm/day)")
    print(sep)
    pre_mon  = series_existing.groupby(series_existing.index.month).mean()
    post_mon = series_new.groupby(series_new.index.month).mean()
    pre_mon.index  = pd.to_datetime(pre_mon.index,  format='%m').strftime('%b')
    post_mon.index = pd.to_datetime(post_mon.index, format='%m').strftime('%b')
    mon_df = pd.DataFrame({'1999-2016': pre_mon, '2017-2026': post_mon})
    mon_df['Delta_pct'] = ((mon_df['2017-2026'] - mon_df['1999-2016'])
                           / mon_df['1999-2016'] * 100)
    print(mon_df.round(3).to_string())

    # -- 3. Sanity checks ------------------------------------------------------
    print("\n" + sep)
    print("3. SANITY CHECKS")
    print(sep)
    ann_mean = series_combined.resample('YE').mean()
    bad = ann_mean[(ann_mean < ANNUAL_PLAUSIBLE[0]) | (ann_mean > ANNUAL_PLAUSIBLE[1])]
    if bad.empty:
        print("  All annual means within plausible range "
              "(%.1f-%.1f mm/day)." % ANNUAL_PLAUSIBLE)
    else:
        print("  WARNING -- years outside plausible range "
              "%.1f-%.1f mm/day:" % ANNUAL_PLAUSIBLE)
        print(bad.round(3).to_string())

    # Flag any obvious sampling artifacts (large jump at 2017 boundary)
    v_dec31 = series_existing['2016-12-25':'2016-12-31'].mean()
    v_jan01 = series_combined['2017-01-01':'2017-01-07'].mean()
    print("  Mean Dec 25-31 2016: %.3f mm/day" % v_dec31)
    print("  Mean Jan  1-7  2017: %.3f mm/day" % v_jan01)
    print("  (Should be similar; both in low-PET dry season.)")

    print("\n" + sep)
    print("Output file: %s" % OUT_FILE)
    print(sep)


def main():
    dry_run = '--dry-run' in sys.argv

    if dry_run:
        print("\n" + "=" * 68)
        print("  DRY-RUN MODE -- nothing written to disk")
        print("=" * 68)

    np.random.seed(42)

    print("\n-- Step 1: Load existing 1999-2016 PET file -------------------------")
    series_existing = load_existing()

    print("\n-- Step 2: Extend 2017-2026 by same-DOY climatological sampling -----")
    series_new = extend_by_climatology(series_existing)

    print("\n-- Step 3: Combine --------------------------------------------------")
    series_combined = pd.concat([series_existing, series_new])
    series_combined = series_combined[~series_combined.index.duplicated(keep='first')]
    series_combined = series_combined.sort_index()
    print("  Combined: %s -> %s  (%d days)"
          % (series_combined.index[0].date(), series_combined.index[-1].date(),
             len(series_combined)))

    print("\n-- Step 4: Summary statistics ---------------------------------------")
    print_summary(series_existing, series_new, series_combined)

    # Step 5: Save -- skipped in dry-run
    if dry_run:
        print("\n  DRY-RUN: output file NOT written.")
        print("  Would save to: %s" % OUT_FILE)
        print("  Re-run without --dry-run to write the file.")
    else:
        print("\n-- Step 5: Save --------------------------------------------------")
        out = series_combined.copy()
        out.index.name = 'Time'
        out.name = 'PET'
        out.to_csv(OUT_FILE, float_format='%.2f', header=True)
        print("  Saved -> %s" % OUT_FILE)


if __name__ == '__main__':
    main()
