#!/usr/bin/env python3
"""
update_tide_data.py
Extend BAM tidal boundary condition files from 2016-12-31 to 2026-04-30 (WY2026).

Method:
  Uses utide (Python tidal harmonic analysis package) to fit harmonic constituents
  to the existing 1999-2016 hourly XTide-predicted data, then predict forward to
  2026-04-30.  The original files were generated by XTide using the NOAA harmonic
  constituents database; utide analysis of that data recovers equivalent constituents
  (validated RMSE ~0.019 m on 2014-2016 holdout for Long Key).

  Region2 and Region3 are derived synthetically per CreateRegion.2.3.tide.R:
    Region2[t] = CapeS[t+3h] * (2/3)   -- lags Cape Sable 3 h, attenuated
    Region3[t] = LongKey[t-3h] * (4/3) -- leads Long Key 3 h, amplified

Output directory: data/Tide/2000_2026/
Boundary config:  data/Boundary/Basin_Tide_Boundary_2000_2026.csv

Usage:
  python update_tide_data.py             # full run -- writes output files
  python update_tide_data.py --dry-run   # stats only -- nothing written

Requirements: pip install utide pandas numpy
"""

import sys
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import utide
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
EXTEND_START = '2017-01-01 00:00'
EXTEND_END   = '2026-04-30 23:00'

DATA_DIR  = Path(__file__).resolve().parent.parent / 'data'
SRC_DIR   = DATA_DIR / 'Tide' / '2000_2016'
OUT_DIR   = DATA_DIR / 'Tide' / '2000_2026'
BOUND_OUT = DATA_DIR / 'Boundary' / 'Basin_Tide_Boundary_2000_2026.csv'

# Station name -> (source file glob prefix, latitude for nodal corrections)
STATIONS = [
    ('Cape_Sable',               25.117),
    ('Long_Key',                 24.820),
    ('Lignumvitae_Key',          24.903),
    ('Snake_Creek',              24.952),
    ('Tavernier_Creek',          25.003),
    ('Garden_Cove',              25.172),
    ('Little_Card_Sound_bridge', 25.288),
]

# New period index (hourly)
NEW_IDX = pd.date_range(EXTEND_START, EXTEND_END, freq='h')

# Full combined index
FULL_START = '1999-09-01 00:00'
FULL_IDX   = pd.date_range(FULL_START, EXTEND_END, freq='h')

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def find_src_file(station_name):
    matches = list(SRC_DIR.glob('%s_*.csv' % station_name))
    if not matches:
        raise FileNotFoundError('No source file for %s in %s' % (station_name, SRC_DIR))
    return matches[0]


def parse_tide_file(path):
    """
    Load an existing BAM tide CSV.
    Returns a pandas Series indexed by datetime, values in metres (demeaned).
    Timestamp format: YYYY-MM-DD HH:MM AM/PM [EDT|EST]
    """
    rows = []
    with open(path, 'r') as f:
        lines = f.readlines()
    for line in lines[1:]:   # skip header
        line = line.strip()
        if not line:
            continue
        parts = line.split(',')
        ts_parts = parts[0].strip().split()
        dt = pd.to_datetime(' '.join(ts_parts[:3]), format='%Y-%m-%d %I:%M %p')
        wl = float(parts[1])
        rows.append((dt, wl))
    idx = pd.DatetimeIndex([r[0] for r in rows])
    vals = np.array([r[1] for r in rows])
    return pd.Series(vals, index=idx, name='WL')


def fit_utide(series, lat):
    """
    Fit harmonic constituents to existing hourly data.
    Returns utide coef Bunch.
    """
    t = series.index.values.astype('datetime64[s]')
    u = series.values.astype(float)
    coef = utide.solve(t, u,
                       lat=lat,
                       method='ols',
                       conf_int='none',
                       verbose=False)
    return coef


def predict_utide(coef, times):
    """
    Predict tidal elevations at given DatetimeIndex using fitted coef.
    Subtracts fitted mean so output is demeaned.
    Returns numpy array.
    """
    t = times.values.astype('datetime64[s]')
    rec = utide.reconstruct(t, coef, verbose=False)
    return rec.h - coef.mean    # subtract fitted mean -> demeaned


def format_timestamp(dt):
    """Format datetime as BAM tide file timestamp string (12-hr, EST label)."""
    return dt.strftime('%Y-%m-%d %I:%M %p EST').replace(' 0', ' ')
    # Note: replace strips leading zero from hour (e.g. ' 01:00' -> ' 1:00')
    # to match original XTide format, though BAM parser handles both


def write_tide_file(series, path):
    """Write combined tide Series to BAM-format CSV."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w') as f:
        f.write('Time, WL.(m).demeaned\n')
        for dt, val in series.items():
            f.write('%s, %.3f\n' % (format_timestamp(dt), val))


def print_fit_stats(name, series_existing, coef, series_pred):
    """Print per-station fit diagnostics."""
    sep = '-' * 60
    n_const = len(coef.name)
    print('\n%s\n  Station : %s' % (sep, name))
    print('  Constituents fitted : %d' % n_const)

    if n_const > 0:
        idx_sort = np.argsort(coef.A)[::-1]
        print('  Top 6 by amplitude (m):')
        for i in idx_sort[:6]:
            print('    %-8s  A=%6.4f m   g=%6.1f deg' % (
                coef.name[i], coef.A[i], coef.g[i]))

    # In-sample RMSE (full existing period)
    t_ex = series_existing.index.values.astype('datetime64[s]')
    rec  = utide.reconstruct(t_ex, coef, verbose=False)
    insample = rec.h - coef.mean
    rmse = np.sqrt(np.mean((series_existing.values - insample)**2))
    print('  In-sample RMSE : %.4f m  (1999-2016)' % rmse)

    # Predicted period stats
    print('  Predicted 2017-2026 :  mean=%.4f m  std=%.4f m  '
          'range=[%.3f, %.3f]' % (series_pred.mean(), series_pred.std(),
                                   series_pred.min(), series_pred.max()))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    dry_run = '--dry-run' in sys.argv

    if dry_run:
        print('\n' + '='*68)
        print('  DRY-RUN MODE -- stats only, no files written')
        print('='*68)
    else:
        OUT_DIR.mkdir(parents=True, exist_ok=True)

    # -----------------------------------------------------------------------
    # Step 1: Process each real station
    # -----------------------------------------------------------------------
    print('\n-- Step 1: Fit and predict each station --------------------------')
    combined = {}   # name -> full combined Series (1999-2026)

    for station_name, lat in STATIONS:
        src = find_src_file(station_name)
        print('\n  Loading %s ...' % src.name)
        series = parse_tide_file(src)
        print('    %d rows  %s -> %s  mean=%.4f m' % (
            len(series), series.index[0].date(), series.index[-1].date(),
            series.mean()))

        print('    Fitting utide (lat=%.3f) ...' % lat, end=' ', flush=True)
        coef = fit_utide(series, lat)
        print('%d constituents.' % len(coef.name))

        # Predict standard new period
        pred_vals = predict_utide(coef, NEW_IDX)
        series_pred = pd.Series(pred_vals, index=NEW_IDX, name='WL')

        if dry_run or True:   # always print stats
            print_fit_stats(station_name, series, coef, series_pred)

        # Combine: existing + predicted
        combined[station_name] = pd.concat([series, series_pred])

        # For Region2 we need Cape Sable extended 3 hours past end
        if station_name == 'Cape_Sable':
            ext_idx = pd.date_range(EXTEND_START,
                                    periods=len(NEW_IDX) + 3, freq='h')
            ext_vals = predict_utide(coef, ext_idx)
            combined['Cape_Sable_ext3'] = pd.concat([
                series,
                pd.Series(ext_vals, index=ext_idx, name='WL')
            ])

    # -----------------------------------------------------------------------
    # Step 2: Derive Region2 and Region3
    # -----------------------------------------------------------------------
    print('\n-- Step 2: Derive Region2 and Region3 ----------------------------')

    # Region2 = Cape_Sable(t+3h) * 2/3
    # Use extended Cape Sable (3 extra hours at end) shifted back 3 positions
    cs_ext = combined['Cape_Sable_ext3']
    region2_vals = cs_ext.values[3:]  * (2.0 / 3.0)   # shift: take values from +3h
    region2_idx  = cs_ext.index[:-3]                   # keep original timestamps
    combined['Region2'] = pd.Series(
        np.round(region2_vals, 3), index=region2_idx, name='WL')
    print('  Region2 : Cape_Sable(t+3h) * 2/3   rows=%d  '
          'range=[%.3f, %.3f]' % (len(combined['Region2']),
                                   combined['Region2'].min(),
                                   combined['Region2'].max()))

    # Region3 = Long_Key(t-3h) * 4/3
    # Prepend last 3 rows of existing Long Key before the new prediction
    lk_existing   = combined['Long_Key'].loc[:'2016-12-31 23:00']
    lk_full       = combined['Long_Key']   # existing + new prediction
    # Build the 3-hour seam: LK values at t-3h for the first 3 new hours
    seam_idx  = pd.date_range('2016-12-31 21:00', periods=3, freq='h')
    seam_vals = lk_existing.loc[seam_idx].values

    # Prediction values shifted back 3h: for t in [2017-01-03 00:00 ...],
    # Region3[t] = LK[t-3h]; for the first 3 new hours use seam
    lk_new_pred = combined['Long_Key'].loc['2017-01-01 00:00':]
    region3_new_vals = np.concatenate([
        seam_vals,
        lk_new_pred.values[:-3]   # LK[t-3h] for t >= 2017-01-01 03:00
    ]) * (4.0 / 3.0)
    region3_new_idx = NEW_IDX

    # Existing Region3 file
    src_r3 = find_src_file('Region3')
    region3_existing = parse_tide_file(src_r3)

    combined['Region3'] = pd.concat([
        region3_existing,
        pd.Series(np.round(region3_new_vals, 3),
                  index=region3_new_idx, name='WL')
    ])
    print('  Region3 : Long_Key(t-3h) * 4/3     rows=%d  '
          'range=[%.3f, %.3f]' % (len(combined['Region3']),
                                   combined['Region3'].min(),
                                   combined['Region3'].max()))

    # Also keep existing Region2 for the existing period
    src_r2 = find_src_file('Region2')
    region2_existing = parse_tide_file(src_r2)
    # Replace with existing + derived new
    region2_new = combined['Region2'].loc['2017-01-01 00:00':]
    combined['Region2'] = pd.concat([region2_existing, region2_new])
    print('  Region2 combined with existing: rows=%d' % len(combined['Region2']))

    # -----------------------------------------------------------------------
    # Step 3: Validate combined files
    # -----------------------------------------------------------------------
    print('\n-- Step 3: Validate combined files ------------------------------')
    # Reference row count: use the first station as baseline.
    # All 9 original files have identical row counts (same DST treatment),
    # so self-consistency is the correct check — not an idealized hourly index.
    station_names_all = [s[0] for s in STATIONS] + ['Region2', 'Region3']
    ref_rows = len(combined[STATIONS[0][0]])
    all_ok = True
    for name in station_names_all:
        s = combined[name]
        n = len(s)
        ok = (n == ref_rows)
        all_ok = all_ok and ok
        # Check 1-hour seam gap at 2016-12-31 23:00 -> 2017-01-01 00:00
        seam_pos = s.index.searchsorted(pd.Timestamp('2017-01-01 00:00'))
        if 0 < seam_pos < len(s):
            seam_gap_h = (s.index[seam_pos] - s.index[seam_pos - 1]).total_seconds() / 3600
            seam_ok = abs(seam_gap_h - 1.0) < 0.01
        else:
            seam_ok = False
            seam_gap_h = float('nan')
        all_ok = all_ok and seam_ok
        print('  %-30s  rows=%6d  seam_gap=%.1fh  %s' % (
            name, n, seam_gap_h, 'OK' if (ok and seam_ok) else 'MISMATCH'))

    print('  (reference row count: %d — all stations should match)' % ref_rows)
    if not all_ok:
        print('\n  WARNING: mismatch(es) above. Check before writing.')

    # -----------------------------------------------------------------------
    # Step 4: Write files (skip in dry-run)
    # -----------------------------------------------------------------------
    OUT_NAMES = {s[0]: s[0] for s in STATIONS}
    OUT_NAMES['Region2'] = 'Region2'
    OUT_NAMES['Region3'] = 'Region3'

    if dry_run:
        print('\n  DRY-RUN: files NOT written.')
        print('  Would write to: %s' % OUT_DIR)
    else:
        print('\n-- Step 4: Write files ------------------------------------------')
        for name in [s[0] for s in STATIONS] + ['Region2', 'Region3']:
            out_name = '%s_1999-09-01_2026-04-30.csv' % name
            out_path = OUT_DIR / out_name
            write_tide_file(combined[name], out_path)
            print('  Saved %s  (%d rows)' % (out_name, len(combined[name])))

        # Write boundary config
        basin_map = [
            (59, 'Cape_Sable'),
            (60, 'Region2'),
            (61, 'Region3'),
            (62, 'Long_Key'),
            (63, 'Long_Key'),
            (64, 'Lignumvitae_Key'),
            (65, 'Snake_Creek'),
            (66, 'Tavernier_Creek'),
            (67, 'Garden_Cove'),
            (68, 'Little_Card_Sound_bridge'),
        ]
        with open(BOUND_OUT, 'w') as f:
            f.write('Basin, Type, File\n')
            for basin_id, stn in basin_map:
                fname = 'data/Tide/2000_2026/%s_1999-09-01_2026-04-30.csv' % stn
                f.write('%d, stage, %s\n' % (basin_id, fname))
        print('\n  Boundary config -> %s' % BOUND_OUT.name)

    print('\n' + '='*68)
    print('Done.')
    print('='*68)


if __name__ == '__main__':
    main()
